### PR TITLE
Fix of "Scccmd initContainer is not the first one to execute"

### LINKED ISSUE #29: Scccmd initContainer is not the first one to execute
Config files created by the scccmd container can't be used in another initContainer because scccmd initContainer is not executed first.

### PR DESCRIPTION
**Pull request by BlackSmith**
This closes #29

### CODE REVIEW

File: pkg/inject/patch.go [hunk 1]
```diff
@@ -71,7 +71,11 @@ func removeVolumes(volumes []corev1.Volume, removed []string, path string) (patc
 	return patch
 }
 
-func addContainer(target, added []corev1.Container, basePath string) (patch []rfc6902PatchOperation) {
+func insertContainer(target, added []corev1.Container, basePath string, args ...string) (patch []rfc6902PatchOperation) {
+	position := "-"
```
Comment (coufalja) [inline pkg/inject/patch.go]: Please don't use args as a wildcard give it meaning, having index 0 a position is confusing
