### PR TITLE
Fix of Config volume is not available in initContainer

### LINKED ISSUE #30: Config volume is not available in initContainer
Trying to use the config volume created by the scccmd in k8s descriptors like
```
      initContainers:
      - name: test-init-s3-bucket
        image: alpine:3.6
        volumeMounts:
        - name: config
          mountPath: /config
        command:
          - sh
          - '-c'
          - 'echo HelloInit && cat /config/config.yaml'
      containers: ...
```
leads to
```
The Deployment "..." is invalid: spec.template.spec.initContainers[0].volumeMounts[0].name: Not found: "config-volume"
```

### PR DESCRIPTION
**Pull request by BlackSmith**
This closes #30

### CODE REVIEW

File: pkg/inject/patch.go [hunk 1]
```diff
@@ -71,7 +71,11 @@ func removeVolumes(volumes []corev1.Volume, removed []string, path string) (patc
 	return patch
 }
 
-func addContainer(target, added []corev1.Container, basePath string) (patch []rfc6902PatchOperation) {
+func insertContainer(target, added []corev1.Container, basePath string, args ...string) (patch []rfc6902PatchOperation) {
+	position := "-"
+	if len(args) > 0 {
+		position = args[0]
```
Comment (coufalja) [inline pkg/inject/patch.go]: Not python :) please don't use the last arg as a wildcard but give it a meaning

File: pkg/inject/patch.go [hunk 2]
```diff
@@ -184,11 +188,16 @@ func createPatch(pod *corev1.Pod, prevStatus *SidecarInjectionStatus, annotation
...
+	patch = append(patch, addAllVolumeMounts(pod.Spec.InitContainers, sic.VolumeMounts, "/spec/initContainers/%d/volumeMounts")...)
+	patch = append(patch, addAllVolumeMounts(pod.Spec.Containers, sic.VolumeMounts, "/spec/containers/%d/volumeMounts")...)
 	patch = append(patch, addVolume(pod.Spec.Volumes, sic.Volumes, "/spec/volumes")...)
+	patch = append(patch, insertContainer(pod.Spec.InitContainers, sic.InitContainers, "/spec/initContainers", "0")...)
 
 	patch = append(patch, updateAnnotation(pod.Annotations, annotations)...)
 
+	res, _ := json.Marshal(patch)
+
+	fmt.Println(fmt.Sprintf("%s", res))
```
Comment (coufalja) [inline pkg/inject/patch.go]: Remove

File: pkg/inject/patch.go [hunk 3]
```diff
@@ -184,11 +188,16 @@ func createPatch(pod *corev1.Pod, prevStatus *SidecarInjectionStatus, annotation
...
-	patch = append(patch, addContainer(pod.Spec.InitContainers, sic.InitContainers, "/spec/initContainers")...)
-	patch = append(patch, addAllVolumeMounts(pod.Spec.Containers, sic.VolumeMounts)...)
+	patch = append(patch, addAllVolumeMounts(pod.Spec.InitContainers, sic.VolumeMounts, "/spec/initContainers/%d/volumeMounts")...)
+	patch = append(patch, addAllVolumeMounts(pod.Spec.Containers, sic.VolumeMounts, "/spec/containers/%d/volumeMounts")...)
 	patch = append(patch, addVolume(pod.Spec.Volumes, sic.Volumes, "/spec/volumes")...)
+	patch = append(patch, insertContainer(pod.Spec.InitContainers, sic.InitContainers, "/spec/initContainers", "0")...)
 
 	patch = append(patch, updateAnnotation(pod.Annotations, annotations)...)
 
+	res, _ := json.Marshal(patch)
```
Comment (coufalja) [inline pkg/inject/patch.go]: Remove
